blog/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.blog_index, name="blog_index"),
    path('<blog_slug>-&id=<blog_id>/', views.blog_detail, name="blog_detail"),
    path('<blog_slug>-&id=<blog_id>/edit/', views.edit_blog, name="edit_blog"),
    path('create/', views.create_blog, name="create_blog"),
]

main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name="index"),
    
    path('donation/', views.donation, name="donation"),
    path('payment/success/', views.success, name='success'),
    path('payment/cancel/', views.cancel, name='cancel'),
    path('create-checkout-session/', views.create_checkout_session, name="create_checkout_session"),

    path('clinic/list/', views.clinin_list, name='clinic_list'),
    path('add/vaccine/', views.add_vaccine, name='add_vaccine'),

    path('add/clinic/', views.add_clinic_info, name='add_clinic_info'),
    path('edit/clinic?id=<clinic_id>/', views.edit_clinic, name='edit_clinic'),
    path('confirm/delete/clinic?id=<clinic_id>/', views.delete_clinic, name='delete_clinic'),
    path('delete/clinic?id=<clinic_id>/', views.delete_it_clinic, name='delete_it_clinic'),
    
    path('book/appointment/', views.book_appointment_view, name='book_appointment'),
    path('user=<user_name>/', views.dashboard, name='dashboard'),
]

vaccinationsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('blogs/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField

class Clinic(models.Model):
    CANADA = 'CA'
    INDIA = 'IN'
    PHONECODE_CHOICES = [
        (CANADA, '+1'),
        (INDIA, '+91'),
    ]
    # address
    clinic_name = models.CharField(max_length=50)
    address_line_one = models.CharField(max_length=100)
    address_line_two = models.CharField(max_length=100)

    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    provinces = models.CharField(max_length=50)

    phone_code = models.CharField(max_length=5, choices=PHONECODE_CHOICES, default=CANADA)
    phone_number = models.CharField(max_length=10)
    # website
    website = models.CharField(max_length=500,  blank=True)
    # opening time 
    opening_time = models.TimeField()
    # closing time
    closing_time = models.TimeField()
    # class Vaccine obj

    def __str__(self):
        return self.clinic_name

class Vaccine(models.Model):
    ModernaVaccine = 'MV'
    PfizerVaccine = 'PV'
    JAJVaccine = 'JV'
    AstrazenecaVaccine = 'AV'
    VACCINE_CHOICES = [
        (ModernaVaccine, 'Moderna vaccine'),
        (PfizerVaccine, 'Pfizer vaccine'),
        (JAJVaccine, 'Johnson and Johnson vaccine'),
        (AstrazenecaVaccine, 'Astrazeneca vaccine'),
    ]
    vaccine_for = models.CharField(max_length=500)
    # vacine name
    vaccine_name = models.CharField(max_length=2, choices=VACCINE_CHOICES)
    # is_avaliable
    is_available = models.BooleanField(default=True)
    # quantity
    quantity = models.PositiveIntegerField()

    clinic = models.ForeignKey('Clinic', on_delete=models.CASCADE)


    def __str__(self):
        # return self.get_vaccine_name_display()
        return self.vaccine_for + " " + self.vaccine_name + " " + str(self.quantity)


class UserAppointBooking(models.Model):
    CANADA = 'CA'
    INDIA = 'IN'
    PHONECODE_CHOICES = [
        (CANADA, '+1'),
        (INDIA, '+91'),
    ]
    ModernaVaccine = 'MV'
    PfizerVaccine = 'PV'
    JAJVaccine = 'JV'
    AstrazenecaVaccine = 'AV'
    VACCINE_CHOICES = [
        (ModernaVaccine, 'Moderna vaccine'),
        (PfizerVaccine, 'Pfizer vaccine'),
        (JAJVaccine, 'Johnson and Johnson vaccine'),
        (AstrazenecaVaccine, 'Astrazeneca vaccine'),
    ]

    FIRST = 'FD'
    SECOND = 'SD'
    DOSE_CHOICES = [
        (FIRST, 'First Dose'),
        (SECOND, 'Second Dose'),
    ]

    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other'),
    ]
    # firts_name
    first_name = models.CharField(max_length=50)
    # last_name
    last_name = models.CharField(max_length=50)
    # user_address
    address_line_one = models.CharField(max_length=100)
    address_line_two = models.CharField(max_length=100)

    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    provinces = models.CharField(max_length=50)
    # DOB
    DOB = models.DateField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1)
    # phone number
    phone_code = models.CharField(max_length=5, choices=PHONECODE_CHOICES, default=CANADA)
    phone_number = models.CharField(max_length=10)
    # Health card (image)
    health_card = models.ImageField(upload_to='images/')
    # which_dose (1st, 2nd)
    which_dose = models.CharField(max_length=2, choices=DOSE_CHOICES)
    # vaccine name
    vaccine_name = models.CharField(choices=VACCINE_CHOICES, max_length=2)

    # date when user will get his/her vaccine
    # time of the day
    choose_date = models.DateTimeField()
    got_dose = models.BooleanField(default=False)
    mossed_dose = models.BooleanField(null=True, blank=True)

    #FOR LANDING PAGE
    # what you must bring alongwith you while visiting pharmacy or vaccine centre (mandatory things 1)

    # Services(2)
    # Doctor information(3) 
    # About pharmacy ambience or environment (4)
    # Donation box(money, blood, clothes and food) (4)

main/forms.py
from django import forms
from django.core.validators import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings
from django.forms.widgets import DateInput


from .models import Vaccine, Clinic, UserAppointBooking

class DashboardForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DashboardForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
        }
        fields = ['username', 'email', 'first_name', 'last_name']


class VaccineForm(forms.ModelForm):

    def __init__(self,  *args, **kwargs):
        # self.request = kwargs.pop('request')
        super(VaccineForm, self).__init__(*args, **kwargs)

    def clean_vaccine_for(self):
        name = self.cleaned_data.get('vaccine_for')
        try:
            match = Vaccine.objects.get(vaccine_for=name)
        except Vaccine.DoesNotExist:
            return name
        raise ValidationError(_('The Location already exist. Please update the value instead adding new.'))

    class Meta:
        model = Vaccine
        fields = ['vaccine_for', 'vaccine_name', 'quantity', 'clinic']


class ClinicForm(forms.ModelForm):

    # def __init__(self,  *args, **kwargs):
    #     self.request = kwargs.pop('request')
    #     super(ClinicForm, self).__init__(*args, **kwargs)

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        is_number = phone_number.isnumeric()

        if not is_number:
            raise ValidationError(_('The value must be a number.'))
        elif len(phone_number) != 10:
            raise ValidationError(_('The value can not be less than or greater than 10.'))
        else:
            return phone_number

    def clean_clinic_name(self):
        name = self.cleaned_data.get('clinic_name')
        try:
            match = Clinic.objects.get(clinic_name=name)
        except Clinic.DoesNotExist:
            return name
        raise ValidationError(_('The Clinic already exist. Please update the value instead adding new.'))
    class Meta:
        model = Clinic
        fields = ['clinic_name', 'address_line_one', 'address_line_two', 'postal_code', 'city', 'provinces',
        'phone_code', 'phone_number', 'website', 'opening_time', 'closing_time']

        widgets = {
                'closing_time': forms.TimeInput(format='%H:%M'),
            }



class UserAppointBookingForm(forms.ModelForm):

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        is_number = phone_number.isnumeric()
        if not is_number:
            raise ValidationError(_('The value must be a number.'))
        elif is_number != 10:
            raise ValidationError(_('The value can not be less than or greater than 10.'))
        else:
            return phone_number

    class Meta:
        widgets = {
            'DOB': DateInput()
        }
        model = UserAppointBooking
        fields = ['first_name', 'last_name', 'address_line_one', 'address_line_two', 'postal_code', 'city', 'provinces',
        'phone_code', 'phone_number', 'DOB', 'gender', 'health_card', 'which_dose', 'vaccine_name', 'choose_date']

       


        

main/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm

from main.forms import DashboardForm, VaccineForm, ClinicForm, UserAppointBookingForm
from main.models import UserAppointBooking, Clinic, Vaccine

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied


import stripe
stripe.api_key = "sk_test_51K0oHcEJY1gb5QocIhDuq1W5WFKbVo59IIF7OrjNW6mWPzctGdIrhURc58koLaKhfP35NR09qlQZYFajpUyZFAnn00j2O6vh1l"
YOUR_DOMAIN = 'http://localhost:8000/'
def create_checkout_session(request):
    if request.method == 'POST':
        checkout_session = stripe.checkout.Session.create(
            # payment_method_types=['card'],
            line_items=[
                {
                    # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
                    'price': 'price_1K0upkEJY1gb5Qocr2Luy6Ym',
                    'quantity': 1,
                },
            ],
            mode='payment',
            success_url=YOUR_DOMAIN + 'payment/success/',
            cancel_url=YOUR_DOMAIN + 'payment/cancel/',
        )
    return redirect(checkout_session.url)


def donation(request):
    return render(request, 'main/checkout.html')

    
def success(request):
    return render(request, 'main/success.html')
    
def cancel(request):
    return render(request, 'main/cancel.html')


def index(request):
    return render(request, 'main/homepage.html', {})


def clinin_list(request):
    clinic_list = Clinic.objects.all()
    return render(request, 'main/clinic_list.html', {'clinic_list': clinic_list})

def delete_clinic(request, clinic_id):
    clinic = get_object_or_404(Clinic, pk=clinic_id)
    return render(request, 'main/confirm_delete.html', {'clinic': clinic})


def delete_it_clinic(request, clinic_id):
    clinic = get_object_or_404(Clinic, pk=clinic_id)
    clinic.delete()
    return redirect('clinic_list')


def edit_clinic(request, clinic_id):
    clinic = get_object_or_404(Clinic, pk=clinic_id)
    form = ClinicForm(instance=clinic)
    if request.method == 'POST':
        form = ClinicForm(request.POST, instance=clinic)
        if form.is_valid():
            form.save()
            messages.info(request, 'Clinic information updated.')
            return redirect('clinic_list')

    dictionary = {'form': form}
    return render(request, 'main/clinic_tem.html', dictionary) 


@login_required
def book_appointment_view(request):
    form = UserAppointBookingForm()
    if request.method == 'POST' or None:
        form = UserAppointBookingForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your appointment is booked.')
            return redirect('index')

    dictionary = {'form': form}
    return render(request, 'main/book_appointment.html', dictionary)


@login_required
def add_clinic_info(request):
    if not request.user.is_superuser:
        raise PermissionDenied()
    form = ClinicForm()
    if request.method == 'POST' or None:
        form = ClinicForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Clinic info added.')
            return redirect('book_appointment')

    dictionary = {'form': form}
    return render(request, 'main/clinic_tem.html', dictionary)


@login_required
def add_vaccine(request):
    if not request.user.is_superuser:
        raise PermissionDenied()
    form = VaccineForm()
    if request.method == 'POST' or None:
        form = VaccineForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Vaccine quantity added.')
            return redirect('add_clinic_info')

    dictionary = {'form': form}
    return render(request, 'main/add_vaccine.html', dictionary)


def dashboard(request, user_name):
    user = User.objects.get(username=user_name)

    password_form = PasswordChangeForm(request.user)
    form = DashboardForm(instance=user)    
    if 'edit_profile' in request.POST and request.method == 'POST':
        form = DashboardForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfuly.')
            return redirect(reverse('dashboard', args=[user.username]))

    elif 'change_password' in request.POST and request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Password changed successfuly.')
            return redirect(reverse('dashboard', args=[user.username]))

    dictionary = {'form': form, 'password_form': password_form}
    return render(request, 'main/dashboard.html', dictionary)
    

templates/main/add_vaccine.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<div class="container-fulid user-styling">
    <div class="container">
        <div class="row post-se">
            <div class="col-lg-4">
              <h1 class="heading-style-1">Add Vaccine info</h1>
              <p>
                  <span style="font-weight: 600;">Note:</span> 
                  <span style="color: rgb(105, 105, 105)">Before you add new locaiton with quantiy please check the list of already given locaiton <a href="#">by clicking here</a> and try to up the quantity there</span>
                </p>
            </div>
            <div class="col-lg-8">
                <div class="form-style-card">
                    <form action="." method="POST" class="form">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}

                        <button type="submit" class="btn btn-success mt-3">Save Vaccine</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/main/book_appointment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<div class="container-fulid user-styling">
    <div class="container">
        <div class="row post-se">
            <div class="col-lg-4">
              <h1 class="heading-style-1">Book your appointment</h1>
            </div>
            <div class="col-lg-8">
                <div class="form-style-card">
                    <form action="." method="POST" class="form">
                        {% csrf_token %}
                        <div class="row mt-3">
                            <div class="form-group col-md-6">
                                {{ form.first_name|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.last_name|as_crispy_field }}                                
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="form-group col-md-6">
                                {{ form.DOB|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.gender|as_crispy_field }}                                
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="form-group col-md-6">
                                {{ form.address_line_one|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.address_line_two|as_crispy_field }}                                
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="form-group col-md-4">
                                {{ form.postal_code|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.city|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.provinces|as_crispy_field }}                                
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="form-group col-md-6">
                                {{ form.phone_code|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.phone_number|as_crispy_field }}                                
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="form-group col-md-12">
                                {{ form.health_card|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-12">
                                {{ form.which_dose|as_crispy_field }}                                
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="form-group col-md-12">
                                {{ form.vaccine_name|as_crispy_field }}                                
                            </div>
                            <div class="form-group col-md-12">
                                {{ form.choose_date|as_crispy_field }}                                
                            </div>
                        </div>

                        <button type="submit" class="btn btn-success mt-3">Save Vaccine</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/main/cancel.html
Cancle

templates/main/checkout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <section>
      <div class="product">
        <img src="https://i.imgur.com/EHyR2nP.png" alt="The cover of Stubborn Attachments" />
        <div class="description">
          <h3>Stubborn Attachments</h3>
          <h5>$20.00</h5>
        </div>
      </div>
      <form action="{% url 'create_checkout_session' %}" method="POST">
        {% csrf_token %}
        <button type="submit" id="checkout-button">Checkout</button>
      </form>
    </section>
  </body>
</html>

templates/main/clinic_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<div class="container-fulid user-styling">
    <div class="container">
        <div class="row post-se">
            <div class="col-lg-4">
              <h1 class="heading-style-1">Clinic List </h1>
              <p>
                <span style="font-weight: 600;">Note: </span>
                <span style="color: rgb(114, 114, 114);"><a href="#">Click here</a> to check already added clinic</span>
            </p>
                <p>
                    <span style="font-weight: 600;">Note: </span>
                    <span style="color: rgb(114, 114, 114);">If the clinic is already exist you can update the infomation or can add quantity on <a href="#">the list</a></span>
                </p>
            </div>
            <div class="col-lg-8">
                {% if clinic_list %}
                {% for clinic in clinic_list %}
                <div class="my-c-card">
                    <div class="clinic-name">
                        <h4>{{ clinic.clinic_name }}</h4>
                    </div>
                    <div class="clinic-vaccine">
                        <div class="row">
                            <div class="col-md-6">
                                <h5>Vaccine:</h5>
                                <div class="state-info">
                                    <ul>
                                        {% if clinic.vaccine_set.all %}
                                        {% for vaccine in clinic.vaccine_set.all %}
                                        <li>
                                            <span class="vaccine-name">{{ vaccine.get_vaccine_name_display }}</span> &bull;
                                            <span>avaliable</span> &bull;
                                            <span>quantity</span>
                                        </li>
                                        {% endfor %}
                                        {% else %}
                                            <strong>There is no vaccine avalible.</strong>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="c-address-info">
                                    <h5><span>Address:</span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>{{ clinic.address_line_one }}</span><br>
                                            {% if clinic.address_line_two %}
                                            <span>{{ clinic.address_line_two }}</span><br>
                                            {% endif %}
                                            <span>{{ clinic.city }}, {{ clinic.provinces }}, {{ clinic.postal_code }}</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="clinic-contact">
                                    <h5><span>Contact info: </span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>{{ clinic.get_phone_code_display }} {{ clinic.phone_number }}</span><br>
                                            <span>website: {{ clinic.website }}</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="clinic-time">
                                    <h5><span>Clinic timing:</span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>Monday to Friday</span> <br>
                                            <span>Opening timing: {{ clinic.opening_time }}</span> &bull;
                                            <span>Closing time: {{ clinic.closing_time }}</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if user.is_superuser %}
                        <a href="{% url 'edit_clinic' clinic.id %}" class="btn btn-info" style="color: white; font-weight: bold;">Edit Clinic</a>
                        <a href="{% url 'delete_clinic' clinic.id %}" class="btn btn-danger" style="color: white; font-weight: bold;">Delete Clinic</a>
                        {% endif %}
                        
                    </div>
                </div>
                {% endfor %}
                {% else %}
                    <strong>There is no clinic added yet</strong>
                    <p><a href="{% url 'add_clinic_info' %}">Click here</a> to add clinic info.</p>
                {% endif %}

                <div class="my-c-card">
                    <div class="clinic-name">
                        <h4>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate, necessitatibus?</h4>
                    </div>
                    <div class="clinic-vaccine">
                        <div class="row">
                            <div class="col-md-6">
                                <h5>Vaccine:</h5>
                                <div class="state-info">
                                    <ul>
                                        <li>
                                            <span class="vaccine-name">vaccine name</span> &bull;
                                            <span>avaliable</span> &bull;
                                            <span>quantity</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="c-address-info">
                                    <h5><span>Address:</span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>184 hollybrook trail</span><br>
                                            <span>Kitchener, orntario, N2R0M2</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="clinic-contact">
                                    <h5><span>Contact info: </span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>+1 5195001610</span><br>
                                            <span>website: jhinjer.herokuapp.com</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="clinic-time">
                                    <h5><span>Clinic timing:</span></h5>
                                    <div class="state-info">
                                        <p>
                                            <span>Monday to priday</span> <br>
                                            <span>Opening timing: 9:00 AM</span> &bull;
                                            <span>Closing time: 10:00 PM</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/main/confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<div class="container-fulid user-styling">
    <div class="container">
        <div class="row post-se">
            <div class="col-lg-4">
              <h1 class="heading-style-1">Confirm Delete </h1>
              <p>
                <span style="font-weight: 600;">Note: </span>
                <span style="color: rgb(114, 114, 114);"><a href="#">Click here</a> to check already added clinic</span>
            </p>
                <p>
                    <span style="font-weight: 600;">Note: </span>
                    <span style="color: rgb(114, 114, 114);">If the clinic is already exist you can update the infomation or can add quantity on <a href="#">the list</a></span>
                </p>
            </div>
            <div class="col-lg-8">
                <strong>Are you sure you want to delete </strong>
                <a href="{% url 'delete_it_clinic' clinic.id %}">{{ clinic }}</a><br>
                <a class="secondaryAction btn btn-danger" href="{% url 'delete_it_clinic' clinic.id %}">Delete</a>
                 
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/main/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block content %}

<div class="container-fulid user-styling">
    <div class="container">
        <div class="row post-se">
            <div class="col-lg-4">
              <h1 class="heading-style-1">Thing that our landing page will have ;)</h1>
            </div>
            <div class="col-lg-8">
                <p><strong>#FOR LANDING PAGE</strong></p>
                <p># what you must bring alongwith you while visiting pharmacy or vaccine centre (mandatory things 1)</p>
                <p># Services(2)</p>
                <p># Doctor information(3)</p>
                <p># About pharmacy ambience or environment (4)</p>
                <p># Donation box(money, blood, clothes and food) (4)</p> 
     
    
    
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/main/success.html
Success